"""unique_path

Revision ID: 0729ee4e8909
Revises: 93ee7fd23674
Create Date: 2023-02-04 15:26:56.104986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0729ee4e8909'
down_revision = '93ee7fd23674'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'file_model', ['path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
