version: "3.3"
services:
  file_storage_api:
    image: file_storage:latest
    container_name: file_storage_api
#    restart: always
    env_file:
      - ../.env
    environment:
      - POSTGRES_HOST=file_storage_postgres
    volumes:
      - ./files:/files
    depends_on:
      - file_storage_postgres
    ports:
      - '9010:9010'
    expose:
      - '9010'
    command: 'sh entrypoint.sh'
    networks:
      - fs_network

  file_storage_postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - fs_network

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./files:/files
    depends_on:
      - service
    ports:
      - "80:80"

networks:
  fs_network:
    external: true