version: "3.3"
services:
  file_storage_api:
    image: file_storage:latest
    container_name: file_storage_api
    env_file:
      - ../.env
    environment:
      - POSTGRES_HOST=file_storage_postgres
      - POSTGRES_PORT=5432
    depends_on:
      - file_storage_postgres
    ports:
      - '9010:9010'
    expose:
      - '9010'
    command: 'sh entrypoint.sh'
    networks:
      - fs_network

  file_storage_postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    networks:
      - fs_network

networks:
  fs_network:
    external: true